import { CommonModule } from '@angular/common'
import { ChangeDetectorRef, Component, inject } from '@angular/core'
import { FormsModule } from '@angular/forms'
import { MatButtonModule } from '@angular/material/button'
import { MAT_DIALOG_DATA, MatDialogModule, MatDialogRef } from '@angular/material/dialog'
import { MatIconModule } from '@angular/material/icon'
import { MatProgressBarModule } from '@angular/material/progress-bar'

export interface FloorplanAiSymbolRecommendation { index:number; deviceName:string; partNumber:string; symbolLabel:string; xRatio:number; yRatio:number; confidence:number; evidence:string; known:boolean; reason:string }
export interface FloorplanAiScaleRecommendation { printedScale:string; rulerLabel:string; startXRatio:number; startYRatio:number; endXRatio:number; endYRatio:number; realWorldFeet:number; confidence:number; evidence:string }
export interface FloorplanAiRecommendationsDialogData { summary?:string; symbols?:FloorplanAiSymbolRecommendation[]; scales?:FloorplanAiScaleRecommendation[]; warnings?:string[]; analyzing?:boolean }
export interface FloorplanAiRecommendationsDialogResult { action:'apply'|'reinspect'|'abort'; symbolIndexes?:number[]; applyScale?:boolean; scaleIndex?:number }
interface FloorplanAiSymbolGroup { key:string; deviceName:string; partNumber:string; symbolLabel:string; confidence:number; known:boolean; reason:string; indexes:number[] }

@Component({
  standalone:true,
  imports:[CommonModule,FormsModule,MatButtonModule,MatDialogModule,MatIconModule,MatProgressBarModule],
  template:`
    <h2 mat-dialog-title>{{analyzing ? 'Analyzing Floorplan' : 'AI Floorplan Recommendations'}}</h2>
    <mat-dialog-content>
      @if(analyzing){
        <section class="analysis-progress" aria-live="polite"><div class="analysis-progress__icon"><mat-icon fontIcon="auto_awesome"></mat-icon></div><div><span class="eyebrow">AI FLOORPLAN REVIEW</span><h3>{{progressMessage}}</h3><p>{{progressDetail}}</p><mat-progress-bar mode="determinate" [value]="progressPercent"></mat-progress-bar><small>{{elapsedSeconds}} seconds elapsed</small></div></section>
      }@else{
        <p class="summary">{{summary}}</p>
        <section><div class="section-heading"><div><span>Device Symbols</span><strong>{{selected.size}} selected placements in {{symbolGroups.length}} groups</strong></div><button mat-button type="button" (click)="toggleAll()">{{allSelectableSelected?'Clear All':'Select All'}}</button></div><div class="table"><div class="row header"><span></span><span>Device</span><span>Part Nbr</span><span>Symbol</span><span>Qty</span><span>Confidence</span></div>
          @for(group of symbolGroups;track group.key){<label class="row" [class.disabled]="!group.known"><span><input type="checkbox" [disabled]="!group.known" [checked]="isGroupSelected(group)" (change)="setGroupSelected(group,$any($event.target).checked)"/></span><span><strong>{{group.deviceName}}</strong>@if(!group.known){<small>{{group.reason}}</small>}</span><span>{{group.partNumber||'—'}}</span><span>{{group.symbolLabel||'—'}}</span><span><strong>{{group.indexes.length}}</strong></span><span>{{group.confidence|percent:'1.0-0'}}</span></label>}
        </div></section>
        <section><div class="section-heading"><div><span>Drawing Scale</span><strong>{{usableScale?'Calibration available':'Review required'}}</strong></div></div>@if(usableScale;as scale){<label class="scale"><input type="checkbox" [(ngModel)]="applyScale"/><span><strong>{{scale.printedScale||scale.rulerLabel}}</strong><small>{{scale.realWorldFeet}} ft ruler · {{scale.confidence|percent:'1.0-0'}} confidence · {{scale.evidence}}</small></span></label>}@else{<div class="notice"><mat-icon fontIcon="straighten"></mat-icon><span>No reliable ruler endpoints and real-world length were returned. Re-inspect or calibrate manually.</span></div>}</section>
        @if(warnings.length){<section><div class="section-heading"><div><span>Warnings</span><strong>{{warnings.length}} items require review</strong></div></div><div class="warnings">@for(warning of warnings;track $index){<div><mat-icon fontIcon="warning_amber"></mat-icon><span>{{warning}}</span></div>}</div></section>}
      }
    </mat-dialog-content>
    <mat-dialog-actions align="end">@if(analyzing){<button mat-stroked-button color="warn" type="button" (click)="abort()"><mat-icon fontIcon="stop_circle"></mat-icon>Abort Analysis</button>}@else{<button mat-button type="button" (click)="close()">Cancel</button><button mat-stroked-button type="button" (click)="reinspect()"><mat-icon fontIcon="refresh"></mat-icon>Re-inspect</button><button mat-flat-button type="button" [disabled]="selected.size===0&&!applyScale" (click)="apply()">Apply Recommendations</button>}</mat-dialog-actions>
  `,
  styles:[`:host{display:grid;grid-template-rows:auto minmax(0,1fr) auto;width:100%;min-width:0;max-height:calc(100vh - 68px);overflow:hidden}mat-dialog-content{display:grid;gap:18px;min-height:0;max-height:none;overflow:auto;overscroll-behavior:contain}.analysis-progress{display:grid;grid-template-columns:auto 1fr;gap:20px;min-height:230px;padding:28px;border:1px solid #24485c;background:#081521}.analysis-progress__icon{display:grid;place-items:center;width:54px;height:54px;border:1px solid #3abce8;background:#102d40;color:#71dcff}.analysis-progress__icon mat-icon{animation:pulse 1.6s ease-in-out infinite}.eyebrow{color:#65d9ff;font-size:.74rem;letter-spacing:.1em}.analysis-progress h3{margin:8px 0;color:#eef9ff}.analysis-progress p{min-height:44px;margin:0 0 18px;color:#9db6c6}.analysis-progress small{display:block;margin-top:10px;color:#7896a8}@keyframes pulse{50%{transform:scale(1.18);filter:drop-shadow(0 0 8px #45d7ff)}}.summary{margin:0;padding:14px;border-left:3px solid #50d6ff;background:#102638;color:#bed4e2}section{border:1px solid #24485c;background:#081521}.section-heading{display:flex;align-items:center;justify-content:space-between;padding:12px 14px;border-bottom:1px solid #24485c}.section-heading div{display:grid;gap:2px}.section-heading span{color:#65d9ff;text-transform:uppercase;font-size:.74rem;letter-spacing:.08em}.section-heading strong{color:#e8f5fc}.table{display:grid;min-width:0}.row{display:grid;grid-template-columns:42px minmax(260px,1.7fr) minmax(130px,.8fr) 90px 70px 110px;align-items:center;border-bottom:1px solid #173748;min-height:48px}.row>span{padding:8px 10px;min-width:0}.row.header{min-height:34px;color:#64d8ff;font-size:.7rem;text-transform:uppercase}.row.disabled{opacity:.58;background:rgba(226,143,48,.08)}.row strong,.row small,.scale span,.scale strong,.scale small{display:block}.row small{margin-top:3px;color:#91acbd}.scale{display:flex;gap:12px;padding:14px}.scale small{margin-top:4px;color:#9eb8c8}.notice{display:flex;gap:10px;padding:14px;color:#e8b15d}.warnings>div{display:flex;gap:10px;padding:10px 14px;border-bottom:1px solid #173748;color:#d9c5a8}.warnings mat-icon{color:#e5a544;flex:none}mat-dialog-actions{border-top:1px solid #24485c}@media(max-width:760px){.table{overflow:auto}.row{min-width:760px}}`]
})
export class FloorplanAiRecommendationsDialog{
  readonly data=inject<FloorplanAiRecommendationsDialogData>(MAT_DIALOG_DATA);private readonly ref=inject(MatDialogRef<FloorplanAiRecommendationsDialog>);private readonly changeDetector=inject(ChangeDetectorRef);analyzing=!!this.data.analyzing;summary=this.data.summary||'';symbols=this.data.symbols||[];scales=this.data.scales||[];warnings=this.data.warnings||[];selected=new Set<number>();applyScale=false;progressMessage='Preparing the floorplan';progressDetail='Loading the source drawing and current BOM device inventory.';progressPercent=4;elapsedSeconds=0
  get symbolGroups():FloorplanAiSymbolGroup[]{const groups=new Map<string,FloorplanAiSymbolGroup>();for(const item of this.symbols){const confidence=Math.round(item.confidence*100)/100;const key=[item.partNumber,item.symbolLabel,item.deviceName,confidence,item.known].join('|');const group=groups.get(key);if(group){group.indexes.push(item.index)}else{groups.set(key,{key,deviceName:item.deviceName,partNumber:item.partNumber,symbolLabel:item.symbolLabel,confidence,known:item.known,reason:item.reason,indexes:[item.index]})}}return [...groups.values()].sort((a,b)=>a.deviceName.localeCompare(b.deviceName)||b.confidence-a.confidence)}
  get usableScale(){return this.scales.find(x=>x.realWorldFeet>0&&x.confidence>=.7&&(x.startXRatio!==x.endXRatio||x.startYRatio!==x.endYRatio))}get allSelectableSelected(){const x=this.symbols.filter(i=>i.known);return x.length>0&&x.every(i=>this.selected.has(i.index))}
  updateProgress(message:string,detail:string,percent:number,elapsed:number){this.progressMessage=message;this.progressDetail=detail;this.progressPercent=percent;this.elapsedSeconds=elapsed;this.changeDetector.detectChanges()}
  showRecommendations(data:{summary:string;symbols:FloorplanAiSymbolRecommendation[];scales:FloorplanAiScaleRecommendation[];warnings:string[]}){this.summary=data.summary;this.symbols=data.symbols;this.scales=data.scales;this.warnings=data.warnings;this.selected=new Set(data.symbols.filter(i=>i.known).map(i=>i.index));this.applyScale=!!this.usableScale;this.analyzing=false;this.changeDetector.detectChanges()}
  isGroupSelected(group:FloorplanAiSymbolGroup){return group.indexes.every(index=>this.selected.has(index))}setGroupSelected(group:FloorplanAiSymbolGroup,c:boolean){group.indexes.forEach(index=>c?this.selected.add(index):this.selected.delete(index))}toggleAll(){this.allSelectableSelected?this.selected.clear():this.symbols.filter(i=>i.known).forEach(i=>this.selected.add(i.index))}close(){this.ref.close()}abort(){this.ref.close({action:'abort'} satisfies FloorplanAiRecommendationsDialogResult)}reinspect(){this.ref.close({action:'reinspect'} satisfies FloorplanAiRecommendationsDialogResult)}apply(){this.ref.close({action:'apply',symbolIndexes:[...this.selected],applyScale:this.applyScale,scaleIndex:this.usableScale?this.scales.indexOf(this.usableScale):-1} satisfies FloorplanAiRecommendationsDialogResult)}
}
